#登录模块
server:
  port: 8887
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?userUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgresql123

  redis:
    host: 127.0.0.1
    database: 2
    port: 6379
    timeout: 3000ms #连接超时时间
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数（负值表示没有限制）
        max-wait: -1ms #复制表示没有时间限制
        max-idle: 5 #连接池最大空闲时间
        min-idle: 0 #连接池最小空闲数



  session:
    store-type: redis



